### ISSUE TITLE
Booting progress bars

### ISSUE THREAD

**Issue by PawelPlesniak** [DUNE-DAQ/drunc#156]
Want `drunc`s boot to look more like that of NanoRC with progress bars instead of verbose output.

**Comment by PawelPlesniak** [comment]
Method - Include children status in fsmcommandresponse definitions for progress bars

**Comment by plasorak** [comment]
I think we have that now?

**Comment by PawelPlesniak** [comment]
Alessandro suggested for each process that gets booted to have its own progress bar. With the upcoming GUI I'm not sure there's much point
