### ISSUE TITLE
Too much jargon and/or required expert knowledge?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/drunc#170]
I recently tried to go through the _fddaq-v5.1.0_ software area instructions, and I stumbled a bit with the suggestions for using `drunc` on that page and on the `drunc` doc pages.  It seems like I need to become somewhat of a `drunc` expert before I can understand how I'm supposed to use it, and that surprises me.  I much prefer interfaces (API, GUI, or whatever) that are easy for the user to use.

A few concrete examples:

- It seems that I'm supposed to start a `drunc` session by typing `drunc-unified-shell <args>`.  Hmm.  What is a unified shell, and why do I need to know about that?
- To drive the system through its transitions, it seems that I need to type `fsm <command>` every time that I want to request a transition.  Why do I need to type "fsm" every time?
- When I forget to give the `fsm start` command a run number argument, I get a long printout telling me that I forgot to provide it, but I'm not provided with a suggestion for how I would do that.  In addition, I couldn't find any examples of an `fsm start` command (with the run_number argument) on any of the "doc" or Wiki pages in the `drunc` repo.  It took a few tries to hit on the right combination:  `fsm start run_number 101`.  Maybe I missed that somewhere, but to help out the next person, I added some suggested "fsm" commands to the _fddaq-v5.1.0_ software area instructions.

I realize that `drunc` is still under development, and I'm filing this Issue to suggest/request that some thought go into making it easier to use for casual users.
Thanks!

**Comment by PawelPlesniak** [comment]
This has been started with a [README.md patch](https://github.com/DUNE-DAQ/drunc/compare/develop...PawelPlesniak-patch-1-1?quick_pull=1) and will be continued tomorrow
