### ISSUE TITLE
Fsm lists incorrect transitions when starting from an incorrect state

### ISSUE THREAD

**Issue by PawelPlesniak** [DUNE-DAQ/drunc#177]
e.g. when running 
```
fsm conf
fsm start_run run_number 1
```
it returns error message 
```
conf is not possible in current state, attempting to construct next transition in sequence conf.
```
which should be
```
conf is not possible in current state, attempting to construct next transition in sequence start.
```

Also the fsm transitions should go through all of the commands and see if any of them are even possibel as per Alessandro's request.

The argument structure should be changed and the optional arguments should be assigned

**Comment by plasorak** [comment]
I think this is issue is no longer relevant. Given we don't have sequences anymore.
