### ISSUE TITLE
Error propagation logic prints error with run number microservice

### ISSUE THREAD

**Issue by PawelPlesniak** [DUNE-DAQ/drunc#230]
When running with the run number usvc, statements of missing mandatory parameters are still supplied. 
Giovanna ran with a config on CRP4 and got messages about missing arguments. Need to get a handle to check if the run number service is being used and amend the mandatory arguments as necessary in [here](https://github.com/DUNE-DAQ/drunc/blob/develop/src/drunc/controller/interface/commands.py?plain=1#L193)

**Comment by plasorak** [comment]
I would advocate using the server-side controller to do that. It's a bit more complicated but that way all the sequences come from the configuration.

**Comment by plasorak** [comment]
This was an artefact of the old implementation of the FSM sequences. See: https://github.com/DUNE-DAQ/drunc/issues/285
