### ISSUE TITLE
Create a simple SSH validator script

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/drunc#245]
For first time users, it's better to make sure that SSH is correctly configured by running a simple scripts that clearly says if drunc isn't able to ssh.

**Comment by PawelPlesniak** [comment]
For review when return, you need to sshkeygen and store it in id_ed25519.pub

**Comment by PawelPlesniak** [comment]
Addressed with PR#[281](https://github.com/DUNE-DAQ/drunc/pull/281)
