### ISSUE TITLE
Should not finding the environment setup script be an error?

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/drunc#259]
Basically, if you try, e.g., running `drunc-unified-shell` after setting up the environment via `dbt-setup-release` rather than via a work area, you'll get this warning:
```
           WARNING  "process_manager_driver": RTE was not supplied in the OKS            process_manager_driver.py:107
                    configuration or in the environment, running without it 
```
and then several paragraphs worth of complaints ending in failure. Is there a use case where we'd want to run without an environment script for the processes? If not, this should be an error causing an exit rather than just a warning.

**Comment by plasorak** [comment]
https://github.com/DUNE-DAQ/drunc/blob/develop/src/drunc/process_manager/process_manager_driver.py#L93C1-L108C1 We can make an exception, yes. To fix the problem here, is `DBT_INSTALL_DIR` setup by `dbt-setup-release`?

**Comment by plasorak** [comment]
This has been fixed here: https://github.com/DUNE-DAQ/drunc/pull/271
