### ISSUE TITLE
Make `boot` interruptible

### ISSUE THREAD

**Issue by PawelPlesniak** [DUNE-DAQ/drunc#283]
SIGINT does not affect `boot`, make it so.

**Comment by PawelPlesniak** [comment]
This already exists for the unfiied shell when the gRPC commands are being generated (as per [here](https://github.com/DUNE-DAQ/drunc/blob/1d339e4e9f69aaa72bfdc2d8055b53a1a8797e66/src/drunc/unified_shell/commands.py#L35)), but still need it when `rich.progress` is displaying `Looking for 'root-controller' on the connectivity service...`

**Comment by plasorak** [comment]
I suspect there are some things related to that here: https://github.com/DUNE-DAQ/drunc/blob/1d339e4e9f69aaa72bfdc2d8055b53a1a8797e66/src/drunc/utils/utils.py#L108C1-L135C19
I cannot understand why it wouldn't interrupt this loading bar with `ctrl-c`. There must be something else catching `SIGINT` somewhere...
