### ISSUE TITLE
Exit Code Incorrect

### ISSUE THREAD

**Issue by TiagoTAlves** [DUNE-DAQ/drunc#49]
When killing processes the information on the broadcast says its exited with exit code 255 but in the Process store, it gives error code 0. (not a major issue but thought it should be recorded)

![image](https://github.com/DUNE-DAQ/drunc/assets/123565780/14753548-cb2c-452d-92b3-d83f5528bdd6)

**Comment by plasorak** [comment]
Is this with SSH?

**Comment by TiagoTAlves** [comment]
This is with SSH PM
